Repository SOPT-31th-Joint-Seminar-5/Client-iOS, pull requests merged in 2022-11, with the labels that each got.

#3 [Feat] 러닝뷰 UI 구현
  Runday/Runday.xcodeproj/project.pbxproj
  Runday/Runday/Global/Extension/UIColor+.swift
  Runday/Runday/Screen/Running/Controller/RunningViewController.swift
  Runday/Runday/Screen/Running/Model/Speed.swift
  Runday/Runday/Screen/Running/RunningViewController.swift
  Runday/Runday/Screen/Running/View/RunGaugeView.swift
  Runday/Runday/Screen/Running/View/RunStepView.swift
Labels: ✨ FEAT, 🐻‍❄️ 떠그

#8 [Feat] 메뉴 뷰 UI 구현
  Runday/Runday/Resource/Asset/Assets.xcassets/menu-etc-right-shift.imageset/Contents.json
  Runday/Runday/Resource/Asset/Assets.xcassets/menu-etc-right-shift.imageset/menu-etc-righit-shift.png
  Runday/Runday/Resource/Asset/Assets.xcassets/menu-left-shift.imageset/Contents.json
  Runday/Runday/Resource/Asset/Assets.xcassets/menu-left-shift.imageset/menu-btn-back.png
  Runday/Runday/Resource/Asset/Assets.xcassets/menu-right-shift.imageset/Contents.json
  Runday/Runday/Resource/Asset/Assets.xcassets/menu-right-shift.imageset/menu-right-shift.png
  Runday/Runday/Screen/Menu/MenuViewController.swift
Labels: ✨ FEAT, 🐹 빠끄

#7 [Feat] 러닝뷰 Animation 기능 구현
  Runday/Runday.xcodeproj/project.pbxproj
  Runday/Runday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Runday/Runday/Screen/Running/Controller/RunningViewController.swift
  Runday/Runday/Screen/Running/Model/RunningTimer.swift
Labels: ✨ FEAT, 🐻‍❄️ 떠그

#10 Feat/#4
  Runday/Runday.xcodeproj/project.pbxproj
  Runday/Runday/Global/Extension/UIColor+.swift
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/Contents.json
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeFour.imageset/Contents.json
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeFour.imageset/KakaoTalk_Image_2022-11-12-00-40-42_001-1.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeFour.imageset/KakaoTalk_Image_2022-11-12-00-40-42_001@2x-1.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeFour.imageset/KakaoTalk_Image_2022-11-12-00-40-42_001@3x-1.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeOne.imageset/Contents.json
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeOne.imageset/KakaoTalk_Image_2022-11-12-00-40-42_002.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeOne.imageset/KakaoTalk_Image_2022-11-12-00-40-42_002@2x.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeOne.imageset/KakaoTalk_Image_2022-11-12-00-40-42_002@3x.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeThree.imageset/Contents.json
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeThree.imageset/KakaoTalk_Image_2022-11-12-00-40-42_001.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeThree.imageset/KakaoTalk_Image_2022-11-12-00-40-42_001@2x.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeThree.imageset/KakaoTalk_Image_2022-11-12-00-40-42_001@3x.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeTwo.imageset/Contents.json
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeTwo.imageset/KakaoTalk_Image_2022-11-12-00-40-42_002-1.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeTwo.imageset/KakaoTalk_Image_2022-11-12-00-40-42_002@2x-1.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/badgeTwo.imageset/KakaoTalk_Image_2022-11-12-00-40-42_002@3x-1.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/profile-image.imageset/Contents.json
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/profile-image.imageset/Rectangle 99.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/profile-image.imageset/Rectangle 99@2x.png
  Runday/Runday/Resource/Asset/Assets.xcassets/ProfileItem/profile-image.imageset/Rectangle 99@3x.png
  Runday/Runday/Screen/MyProfile/Cell/BadgeCell.swift
  Runday/Runday/Screen/MyProfile/Cell/ExerciseCell.swift
  Runday/Runday/Screen/MyProfile/Cell/MenuCell.swift
  Runday/Runday/Screen/MyProfile/Cell/ProfileTableViewCellType.swift
  Runday/Runday/Screen/MyProfile/Controller/MyProfileViewController.swift
  Runday/Runday/Screen/MyProfile/Model/BadgeModel.swift
  Runday/Runday/Screen/MyProfile/Model/ExerciseModel.swift
  Runday/Runday/Screen/MyProfile/Model/MenuModel.swift
  Runday/Runday/Screen/MyProfile/Model/ProfileModel.swift
  Runday/Runday/Screen/MyProfile/View/MyProfileView.swift
Labels: ✨ FEAT, 🐶 헌

#13 [Feat] 화면 전환 기능 구현
  Runday/Runday/Screen/Home/Controllers/HomeViewController.swift
  Runday/Runday/Screen/Home/Controllers/LevelExerciseViewController.swift
  Runday/Runday/Screen/Home/Controllers/MyExerciseViewController.swift
  Runday/Runday/Screen/Home/Controllers/PersonalExerciseViewController.swift
  Runday/Runday/Screen/Home/Controllers/TimeExerciseViewController.swift
  Runday/Runday/Screen/Menu/MenuViewController.swift
  Runday/Runday/Screen/Running/Controller/RunningViewController.swift
Labels: ✨ FEAT, 🐻‍❄️ 떠그

#15 [Feat] 네트워크 통신 세팅 및 열거형 Target 구현
  Runday/Runday.xcodeproj/project.pbxproj
  Runday/Runday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Runday/Runday/Network/Base/BaseTargetType.swift
  Runday/Runday/Network/Base/Encodable+.swift
  Runday/Runday/Network/Base/NetworkLoggerPlugin.swift
  Runday/Runday/Network/Base/URLConstant.swift
  Runday/Runday/Network/DataModel/Home/LikeRequestDto.swift
  Runday/Runday/Network/DataModel/Home/LikeResponseDto.swift
  Runday/Runday/Network/DataModel/Home/TimeExerciseResponseDto.swift
  Runday/Runday/Network/DataModel/MyProfile/MyProfileResponseDto.swift
  Runday/Runday/Network/DataModel/NetworkError.swift
  Runday/Runday/Network/Service/Home/LikeService.swift
  Runday/Runday/Network/Service/Home/TimeExerciseService.swift
  Runday/Runday/Network/Service/MyProfile/MyProfileService.swift
  Runday/Runday/Network/URLConstant.swift
  Runday/Runday/Resource/Application/Info.plist
Labels: ✨ FEAT, 🐹 빠끄

#17 [Chore] API 템플릿 수정
  Runday/Runday.xcodeproj/project.pbxproj
  Runday/Runday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Runday/Runday/Global/Constant/UserModel.swift
  Runday/Runday/Network/API/Home/LikeAPI.swift
  Runday/Runday/Network/API/Home/TimeExerciseAPI.swift
  Runday/Runday/Network/API/MyProfile/MyProfileAPI.swift
  Runday/Runday/Network/Base/NetworkConstant.swift
  Runday/Runday/Network/Base/NetworkLoggerPlugin.swift
  Runday/Runday/Network/Base/NetworkResult.swift
  Runday/Runday/Network/DataModel/CommonRequestDTO.swift
  Runday/Runday/Network/DataModel/Home/LikeRequestDto.swift
  Runday/Runday/Network/DataModel/Home/LikeResponseDto.swift
  Runday/Runday/Network/DataModel/Home/TimeExerciseResponseDto.swift
  Runday/Runday/Network/DataModel/MyProfile/MyProfileResponseDto.swift
  Runday/Runday/Network/DataModel/NetworkError.swift
  Runday/Runday/Network/Service/Home/LikeService.swift
  Runday/Runday/Network/Service/Home/TimeExerciseService.swift
  Runday/Runday/Network/Service/MyProfile/MyProfileService.swift
  Runday/Runday/Screen/Base/BaseTabBarController.swift
  Runday/Runday/Screen/Crew/CrewViewController.swift
Labels: ✅ CHORE, 🐻‍❄️ 떠그

#22 [Feat] 러닝뷰 하단 런게이지 기능 구현
  Runday/Runday.xcodeproj/project.pbxproj
  Runday/Runday/Screen/Running/Controller/RunningViewController.swift
  Runday/Runday/Screen/Running/Model/RunGaugeModel.swift
  Runday/Runday/Screen/Running/View/RunGaugeStackView.swift
  Runday/Runday/Screen/Running/View/RunGaugeView.swift
  Runday/Runday/Screen/Running/View/RunStepView.swift
Labels: ✨ FEAT, 🐻‍❄️ 떠그

#24 [Feat] Circle ProgressBar 구현
  Runday/Runday.xcodeproj/project.pbxproj
  Runday/Runday/Screen/History/RunStepView.swift
  Runday/Runday/Screen/History/RunningViewController.swift
  Runday/Runday/Screen/Home/Controllers/LevelExerciseViewController.swift
  Runday/Runday/Screen/Home/Controllers/MyExerciseViewController.swift
  Runday/Runday/Screen/Home/Controllers/PersonalExerciseViewController.swift
  Runday/Runday/Screen/Home/Controllers/TimeExerciseViewController.swift
  Runday/Runday/Screen/Running/Controller/CircleRunningViewController.swift
  Runday/Runday/Screen/Running/Model/RunGaugeModel.swift
  Runday/Runday/Screen/Running/Model/RunningModel.swift
  Runday/Runday/Screen/Running/Model/RunningTimer.swift
  Runday/Runday/Screen/Running/View/RunCircleProgressView.swift
  Runday/Runday/Screen/Running/View/RunCircleStepView.swift
  Runday/Runday/Screen/Running/View/RunGaugeStackView.swift
  Runday/Runday/Screen/Running/View/RunGaugeView.swift
  Runday/Runday/Screen/Running/View/RunStepView.swift
Labels: ✨ FEAT, 🐻‍❄️ 떠그

#27 [Feat] Home 뷰 좋아요 API 연동
  Runday/Runday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Runday/Runday/Screen/Home/Controllers/TimeExerciseViewController.swift
  Runday/Runday/Screen/Home/View/Reusable/ExerciseCollectionViewCell.swift
Labels: ✨ FEAT, 🐹 빠끄

#28 [Feat]: 마이 페이지 서버연결 #25
  Runday/Runday/Network/API/MyProfile/MyProfileAPI.swift
  Runday/Runday/Network/DataModel/MyProfile/MyProfileResponseDto.swift
  Runday/Runday/Screen/MyProfile/Cell/ExerciseCell.swift
  Runday/Runday/Screen/MyProfile/Controller/MyProfileViewController.swift
  Runday/Runday/Screen/MyProfile/View/MyProfileView.swift
Labels: ✨ FEAT, 🐶 헌
